[streetwomanfighter]
title = "Mnet 스트릿 우먼 파이터 ─ 네이버TV"
url = "https://tv.naver.com/cjenm.STREETWOMANFIGHTER/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[singagain2]
title = "JTBC 싱어게인2 ─ 네이버TV"
url = "https://tv.naver.com/jtbc.singagain2/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[myteenagegirl]
title = "MBC 방과후 설렘 ─ 네이버TV"
url = "https://tv.naver.com/mbc.myteenagegirl/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"